### ISSUE TITLE
Do you have the latest version of CentOS to download, such as CentOS 9？

### ISSUE THREAD

**Issue by dong-lufei** [KNOXDEV/wsl#2]
Is the latest version of ubuntu installed like this: scoop install wsl-ubuntu2204

**Comment by KNOXDEV** [comment]
I'll interpret this as two questions:

First, Microsoft does not provide an officially supported CentOS image, but I suppose I could still add it by using the release feed here: https://github.com/mishamosher/CentOS-WSL/releases

Second, the latest version of Ubuntu IS available for download on the microsoft store, but this repo has not been updated with the latest files.

I will attempt to fix both issues, when I do, I will update this issue, and it would be great if you could make sure it works for me.

**Comment by KNOXDEV** [comment]
Just pushed an update that should allow you to do the following:

```
scoop install wsl-centos9
scoop install wsl-ubuntu2204
```

Please try them out and open a new issue if you run into any problems
