### ISSUE TITLE
ubuntu2004 does not work

### ISSUE THREAD

**Issue by SiyuChern** [KNOXDEV/wsl#4]
Microsoft has made an in-place upgrade to wsl-ubuntu2004, leading to the current manifest failing to install ubuntu2004. Please see below:

scoop install wsl/wsl-ubuntu2004
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
WARN  To disable this warning, run 'scoop config aria2-warning-enabled false'.
Installing 'wsl-ubuntu2004' (20.04) [64bit] from wsl bucket
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 47aeb9|OK  |    13MiB/s|C:/Users/siyu/scoop/cache/wsl-ubuntu2004#20.04#https_aka.ms_wslubuntu2004
Download: Status Legend:
Download: (OK):download completed.
WARN  Warning: No hash in manifest. SHA256 for 'wsl-ubuntu2004#20.04#https_aka.ms_wslubuntu2004' is:
    be91806d4c9250eb275cafb3559aa44257f320564a17a824d29d5f937be42025
Running installer script...
Linking ~\scoop\apps\wsl-ubuntu2004\current => ~\scoop\apps\wsl-ubuntu2004\20.04
**Creating shortcut for Ubuntu 20.04 LTS (ubuntu2004.exe) failed: Couldn't find C:\Users\siyu\scoop\apps\wsl-ubuntu2004\current\ubuntu2004.exe**

**Comment by SiyuChern** [comment]
A new wsl-ubuntu2004.json that works:

```
{
    "homepage": "https://www.microsoft.com/store/apps/9n6svws3rx71",
    "description": "Ubuntu 20.04 LTS on WSL",
    "license": "Proprietary",
    "version": "20.04",
    "url": "https://aka.ms/wslubuntu2004",
    "architecture": {
        "64bit": {
            "installer": {
                "script": [
                    "Get-Item \"$dir\\wslubuntu2004\" | Rename-Item -NewName \"ubuntu2004.zip\"",
                    "Expand-Archive -Path \"$dir\\ubuntu2004.zip\" -DestinationPath \"$dir\"",
                    "Remove-Item \"$dir\\ubuntu2004.zip\"",
                    "Get-Item \"$dir\\*x64.appx\" | Rename-Item -NewName \"ubuntu2004.zip\"",
                    "Expand-Archive -Force -Path \"$dir\\ubuntu2004.zip\" -DestinationPath \"$dir\"",
                    "Remove-Item \"$dir\\ubuntu2004.zip\"",
                    "Get-Item \"$dir\\*.appx\" | Remove-Item"
                ]
            }
        },
        "arm64": {
            "installer": {
                "script": [
                    "Get-Item \"$dir\\wslubuntu2004\" | Rename-Item -NewName \"ubuntu2004.zip\"",
                    "Expand-Archive -Path \"$dir\\ubuntu2004.zip\" -DestinationPath \"$dir\"",
                    "Remove-Item \"$dir\\ubuntu2004.zip\"",
                    "Get-Item \"$dir\\*ARM64.appx\" | Rename-Item -NewName \"ubuntu2004.zip\"",
                    "Expand-Archive -Force -Path \"$dir\\ubuntu2004.zip\" -DestinationPath \"$dir\"",
                    "Remove-Item \"$dir\\ubuntu2004.zip\"",
                    "Get-Item \"$dir\\*.appx\" | Remove-Item"
                ]
            }
        }
    },
    "shortcuts": [
        [
            "ubuntu.exe",
            "Ubuntu 20.04 LTS"
        ]
    ],
    "uninstaller": {
        "script": "wslconfig /u Ubuntu-20.04"
    }
}

```

**Comment by SiyuChern** [comment]
Also, the current wsl-ubuntu2004 already includes wsl-ubuntu2004-arm, so we do not need wsl-ubuntu2004-arm.json

**Comment by KNOXDEV** [comment]
Thanks for reporting, I've pushed the fix. Let me know if there are any further problems.
